// ---------------------------------------------------------------------------
// Financial institution alias map.
// Maps LIXI / LMG financial institution names to Quickli liability lender names.
// Only explicit aliases -- identity mappings omitted since the lookup falls
// through to 'Other' for unmatched values.
// ---------------------------------------------------------------------------

const financialInstitutionMap: Record<string, string> = {
  'ANZ Bank': 'ANZ',
  'Australian Military Bank Ltd': 'Australian Military Bank',
  'Bank of Sydney Ltd': 'Bank of Sydney',
  'Better Mortgage Corporation': 'Better Mortgage Management',
  BOQ: 'Bank of Queensland',
  'Brighten Home Loans': 'Brighten',
  CBA: 'Commonwealth Bank',
  Citibank: 'Citi',
  'Community First Credit Union Limited': 'Community First Credit Union',
  'G and C Mutual Bank Limited': 'G&C Mutual Bank',
  Humm: 'humm90',
  'IMG Ltd': 'IMB Bank',
  LaTrobe: 'La Trobe Financial',
  Liberty: 'Liberty Financial',
  Macquarie: 'Macquarie Bank',
  Paramount: 'Paramount Mortgage Services',
  "People's Choice Credit Union": "People's Choice",
  Pepper: 'Pepper Money',
  RESIMAC: 'Resimac',
  'St George': 'St. George Bank',
  'Suncorp Metway': 'Suncorp Metway Advances Corporation Pty Ltd',
  'Teachers Mutual': 'Teachers Mutual Bank',

  // LMG Other FI Mapping
  'AMP Australia': 'AMP',
  'ANZ Australia': 'ANZ',
  'Assetline Capital': 'Assetline Capital Pty Ltd',
  Athena: 'Athena Home Loans',
  'Australian Financial': 'Australian Financial Holdings Pty Ltd',
  BankWest: 'Bankwest',
  'Better Choice Home Loans': 'Better Choice',
  'Beyond Bank': 'Beyond Bank Australia',
  "Buyers Choice": "Buyer's Choice Home Loan Advisory Service Pty Ltd",
  FirstMac: 'Firstmac',
  'Granite Homeloans': 'Granite Home Loans',
  Hejaz: 'Hejaz Islamic Credit Solutions Pty Ltd',
  HomeStart: 'Homestart Finance',
  'Ma Money': 'MA Money Financial Services Pty Ltd',
  MoneyQuest: 'Money Quest Australia Pty Ltd',
  MyState: 'MyState Bank Limited',
  'National Australia Bank': 'NAB',
  'ORDE Financial': 'ORDE Financial Pty Ltd',
  'Pepper Money': 'Pepper Money',
  'Virgin Money Australia': 'Virgin Money',
  'Wave Money': 'Wave Money Pty Ltd',

  // LMG Commercial FI Mapping
  'Assetline Commercial': 'Assetline Capital Pty Ltd',
  'Bank of Melbourne Commercial': 'Bank of Melbourne',
  'Bank of Queensland Commercial': 'Bank of Queensland',
  'Bank SA Commercial': 'Bank SA',
  'Commonwealth Commercial': 'Commonwealth Bank',
  'IMB Commercial': 'IMB Bank',
  'Judo Bank Commercial': 'Judo Bank',
  'La Trobe Commercial': 'La Trobe Financial',
  'Liberty Commercial': 'Liberty Financial',
  'Macquarie Commercial': 'Macquarie Bank',
  'Medfin Finance': 'Medfin',
  'NAB Commercial': 'NAB',
  'Pepper Money Commercial': 'Pepper Money',
  'Prime Capital': 'Prime Capital Securities Pty Ltd',
  'RedZed Commercial': 'RedZed',
  'Scottish Pacific Commercial': 'Scottish Pacific Business Finance',
  'St George Commercial': 'St. George Bank',
  'Suncorp Commercial/Business': 'Suncorp',
  'Westpac Commercial': 'Westpac',

  // LMG Asset Finance Mapping
  'ANZ Asset Finance': 'ANZ',
  'Bank of Queensland Asset Finance': 'Bank of Queensland',
  'CBA Asset Finance': 'Commonwealth Bank',
  'Early Pay': 'earlypay',
  'Firstmac Car Loans': 'Firstmac',
  FlexiCommercial: 'Flexicommercial Pty Ltd',
  'Judo Bank Asset Finance': 'Judo Bank',
  'NAB Asset Finance': 'NAB',
  'Pepper Asset Finance': 'Pepper Money',
  'Plenti Auto Finance': 'Plenti',
  'Resimac Asset Finance': 'Resimac',
  'Scottish Pacific Asset Finance': 'Scottish Pacific Business Finance',
  WISR: 'Wisr',

  // LMG Personal/Other Lending Mapping
  'Alex Bank': 'Prospa',
  MoneyPlace: 'MoneyPlace',
  'NOW Finance': 'NOW Finance',
  'Pepper Money Personal Loans': 'Pepper Money',
  'Society One': 'SocietyOne',
  Allianz: 'Allianz',
  Banjo: 'Prospa',
  'Moula (PL)': 'Moula',
  OnDeck: 'OnDeck',
  Prospa: 'Prospa',
  Shift: 'Shift',
};

export default financialInstitutionMap;
